### ISSUE TITLE
Intended? Tablet App doesn't rotate, stuck in portrait mode

### ISSUE THREAD

**Issue by RebornSerenity** [itsjavi/supereffective-assets#17]
Most tablets sit landscape when they are in a stand, and It doesn't rotate properly, intended, possibly, but highly frustrating to work with when you're using a tablet to do the pokedex. If you could add in rotation, that would be awesome.

**Comment by RebornSerenity** [comment]
I'd also like to mention, performance on a tablet is really horrible, it's extremely responsive on my PC, but when you click on a pokemon it takes at least 5-10 seconds for it to laggily turn "caught" it doesn't work well on a tablet, at all sadly.

**Comment by itsjavi** [comment]
all that you mention seems an issue of your tablet, not the website. 

I would also need to know your tablet model, some old models have problems with modern websites.

rotation is not blocked as you can see in the screenshot ![image](https://user-images.githubusercontent.com/122741/209435987-8b231cb5-4cee-4775-92fc-27672511a0ea.png)

**Comment by itsjavi** [comment]
Also, the right place for website issues is https://github.com/itsjavi/supereffective.gg/issues
this repo is only for data and graphics.

Thanks
